title: Thực hành Học Máy với Scikit-Learn, Keras & TensorFlow
logo: /assets/img/logo.svg
description: Một dự án của MLBVN Group
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

plugins:
  - jekyll-octicons
